dist: xenial
sudo: required
dist: trusty
language: c

before_install:
    # update package list
    - sudo add-apt-repository -y ppa:waja/trusty-backports && sudo apt-get update -qq

install:
    # install packages needed for mk-build-deps
    - sudo apt-get install -qq --no-install-recommends devscripts equivs
    # pull build deps from debian/control
    - sudo mk-build-deps -ir -t "apt-get --yes --no-install-recommends"
    # remove packages needed for mk-build-deps
    - sudo apt-get purge -qq equivs
    - sudo apt-get autoremove -qq

script:
    # build the debian package
    - dpkg-buildpackage -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc

env:
  global:
    # travis encrypt -r waja/imapsync GITHUBTOKEN=XXXXXX (https://help.github.com/articles/creating-an-access-token-for-command-line-use / http://docs.travis-ci.com/user/encryption-keys/)
    secure: "TXWTG98WlH91eP8iGuxU6iDG8f7DTum036wzqokIsiW6FIkjQTAcYB21WULKjHsPFPHVLj44zuzMbhdk9DZNK10iDLa7pHudrvYuevt25GwFNdDkYk4YZj7BJ2NNqROYQ7MYNhXYHQnI+HsmU+u3q2ZNAQRDxjB6esDvYBRE7I0="

after_success:
    - mkdir -p debian/build/release/
    - for FILE in $(dcmd ../*.changes); do cp ../$(basename $FILE) debian/build/release/; done
    - debian/bin/github-release.sh "$TRAVIS_REPO_SLUG" "debian/`head -1 debian/changelog | awk -F'[()]' '{print $2}' | awk -F'+' '{print $1}'`" debian/build/release/*
#notifications:
#  email: false
