dist: xenial
os: linux
language: c

before_install:
    # update package list
    - sudo add-apt-repository -y ppa:mc-1/stream-schedule && sudo apt-get update -qq

install:
    # install packages needed for mk-build-deps
    - sudo apt-get install -qq --no-install-recommends devscripts equivs
    # install debhelper 10 (from backports)
    - sudo apt-get install -qq --no-install-recommends -t xenial-backports debhelper
    # pull build deps from debian/control
    - sudo mk-build-deps -ir -t "apt-get -o Debug::pkgProblemResolver=yes --yes --no-install-recommends" debian/control
    # remove packages needed for mk-build-deps
    - sudo apt-get purge -qq equivs
    - sudo apt-get autoremove -qq

script:
    # build the debian package
    - dpkg-buildpackage -uc -us

after_script:
    # run lintian after build
    - sudo apt-get install -qq --no-install-recommends lintian
    - lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.deb && lintian --info --display-info --display-experimental --pedantic --show-overrides ../*.dsc

env:
  global:
    # travis encrypt -r waja/imapsync GITHUBTOKEN=XXXXXX (https://help.github.com/articles/creating-an-access-token-for-command-line-use / http://docs.travis-ci.com/user/encryption-keys/)
    secure: "dg0wtJ+/H6kk4W8dFHehnnOxCoUOFmKcDFK15einqqVNSrGsut1dv2D2b5SMDiMCAXXhTxbRE413vt4+6XNVl8YxQOrBmU1bXgbcUAf7wqI3yo5Sh0y4f6kWLx46ngHtdF+yxGN00ko6+yZPXHgpx2Dz6T2PFgHmxNhiLEkIY8s="

after_success:
    - mkdir -p debian/build/release/
    - for FILE in $(dcmd ../*.changes); do cp ../$(basename $FILE) debian/build/release/; done
    - export RELEASE_PKG_FILE=$(find debian/build/release/ -type f)
    - debian/bin/github-release.sh "$TRAVIS_REPO_SLUG" "debian/`head -1 debian/changelog | awk -F'[()]' '{print $2}' | awk -F'+' '{print $1}'`" debian/build/release/*
#notifications:
#  email: false

deploy:
  provider: releases
  token:
    secure: "dg0wtJ+/H6kk4W8dFHehnnOxCoUOFmKcDFK15einqqVNSrGsut1dv2D2b5SMDiMCAXXhTxbRE413vt4+6XNVl8YxQOrBmU1bXgbcUAf7wqI3yo5Sh0y4f6kWLx46ngHtdF+yxGN00ko6+yZPXHgpx2Dz6T2PFgHmxNhiLEkIY8s="
  file: '${RELEASE_PKG_FILE}'
  skip_cleanup: true
  on:
    tags: true
